FROM romeoz/docker-apache-php:7.3

RUN apt-get update \
    && apt-get install -y php7.3-sqlite3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/app/

EXPOSE 80 443

CMD ["/sbin/entrypoint.sh"]
